/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.daw.finalchallenge;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alumnado
 */
public class DBPanel extends javax.swing.JPanel {

    /**
     * Creates new form DBPanel
     */
    public DBPanel() {
        initComponents();
    }

    public static void main(String[] args) {
        DBPanel fishDB = new DBPanel();
        JFrame window = new JFrame("FishDatabase");
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setContentPane(fishDB);
        window.setSize(825, 400);
        window.setLocation(100, 0);
        window.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JInsertButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        JUpdateButton = new javax.swing.JButton();
        JDeleteButton = new javax.swing.JButton();
        JQueryButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JInsertEsp = new javax.swing.JButton();
        JUpdateEsp = new javax.swing.JButton();
        JDeleteEsp = new javax.swing.JButton();
        JQueryEsp = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 28, -1, -1));

        jTextField1.setMinimumSize(new java.awt.Dimension(64, 100));
        jTextField1.setPreferredSize(new java.awt.Dimension(120, 22));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 50, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 140, -1, -1));

        JInsertButton.setText("INSERT");
        JInsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JInsertButtonActionPerformed(evt);
            }
        });
        add(JInsertButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 269, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alimentacion:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 28, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descripción:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 78, -1, -1));

        jTextField5.setPreferredSize(new java.awt.Dimension(120, 22));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 100, -1, -1));

        JUpdateButton.setText("UPDATE");
        JUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUpdateButtonActionPerformed(evt);
            }
        });
        add(JUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 269, -1, -1));

        JDeleteButton.setText("DELETE");
        JDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDeleteButtonActionPerformed(evt);
            }
        });
        add(JDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 269, -1, -1));

        JQueryButton.setText("QUERY");
        JQueryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JQueryButtonActionPerformed(evt);
            }
        });
        add(JQueryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 269, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Familia", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 25, 333, 220));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Acciones sobre la tabla \"Alimentacion\"");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 247, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 25, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alimentacion:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 121, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Familia:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 75, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 171, -1, -1));

        jTextField2.setPreferredSize(new java.awt.Dimension(120, 22));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 47, -1, -1));

        jTextField3.setPreferredSize(new java.awt.Dimension(120, 22));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 93, -1, -1));

        jTextField4.setPreferredSize(new java.awt.Dimension(120, 22));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 143, -1, -1));

        jTextField6.setPreferredSize(new java.awt.Dimension(120, 22));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 193, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Acciones sobre la tabla \"especies\"");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 247, -1, -1));

        JInsertEsp.setText("INSERT");
        JInsertEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JInsertEspActionPerformed(evt);
            }
        });
        add(JInsertEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 269, -1, -1));

        JUpdateEsp.setText("UPDATE");
        JUpdateEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUpdateEspActionPerformed(evt);
            }
        });
        add(JUpdateEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 269, -1, -1));

        JDeleteEsp.setText("DELETE");
        JDeleteEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDeleteEspActionPerformed(evt);
            }
        });
        add(JDeleteEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 269, -1, -1));

        JQueryEsp.setText("QUERY");
        JQueryEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JQueryEspActionPerformed(evt);
            }
        });
        add(JQueryEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 269, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\eloyt\\Desktop\\desktop-wallpaper-ocean-under-sea.jpg")); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void JInsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JInsertButtonActionPerformed
        Alimentacion a = new Alimentacion(jTextField1.getText(), jTextField5.getText());
        SQLActionsOnAlimentacion.insertData(a);
        jTextArea1.setText("¡Nuevo tipo de alimentación ragistrado!");
    }//GEN-LAST:event_JInsertButtonActionPerformed

    private void JUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUpdateButtonActionPerformed
        Alimentacion a = new Alimentacion(jTextField1.getText(), jTextField5.getText());
        SQLActionsOnAlimentacion.updateData(a);
        jTextArea1.setText("¡Update realizada correctamente!");
    }//GEN-LAST:event_JUpdateButtonActionPerformed

    private void JDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDeleteButtonActionPerformed
        Alimentacion a = new Alimentacion(jTextField1.getText());
        SQLActionsOnAlimentacion.deleteData(a);
        jTextArea1.setText("¡Nooooo, murió de inanición! D:");
    }//GEN-LAST:event_JDeleteButtonActionPerformed

    private void JQueryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JQueryButtonActionPerformed
        Alimentacion a = new Alimentacion(jTextField1.getText());
        a = SQLActionsOnAlimentacion.query(a);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        List<Especies> especies = a.getEspecie();
        jTextArea1.setText(a.getAlimentacion() + ":\n" + a.getDescripcion());
        for (Especies especie : especies) {
            model.addRow(new Object[]{especie.getNombre(), especie.getFamilia(), especie.getTipo()});
        }
        jTextField5.setText(a.getDescripcion());
    }//GEN-LAST:event_JQueryButtonActionPerformed

    private void JInsertEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JInsertEspActionPerformed
        Especies e = new Especies(jTextField2.getText(), jTextField3.getText(), jTextField4.getText(), jTextField6.getText());
        SQLActionsOnEspecies.insertData(e);
        jTextArea1.setText("¡Nueva especie ragistrada!");
    }//GEN-LAST:event_JInsertEspActionPerformed

    private void JUpdateEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUpdateEspActionPerformed
        Especies e = new Especies(jTextField2.getText(), jTextField3.getText(), jTextField4.getText(), jTextField6.getText());
        SQLActionsOnEspecies.updateData(e);
        jTextArea1.setText("¡Update realizada correctamente!");
    }//GEN-LAST:event_JUpdateEspActionPerformed

    private void JDeleteEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDeleteEspActionPerformed
        Especies e = new Especies(jTextField2.getText());
        SQLActionsOnEspecies.deleteData(e);
        jTextArea1.setText("¡Nooooo, la especie se ha extinguido por tu culpa! D:");
    }//GEN-LAST:event_JDeleteEspActionPerformed

    private void JQueryEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JQueryEspActionPerformed
        Especies e = new Especies(jTextField2.getText());
        e = SQLActionsOnEspecies.query(e);
        jTextField3.setText(e.getFamilia());
        jTextField4.setText(e.getAlimentacion());
        jTextField6.setText(e.getTipo());
    }//GEN-LAST:event_JQueryEspActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JDeleteButton;
    private javax.swing.JButton JDeleteEsp;
    private javax.swing.JButton JInsertButton;
    private javax.swing.JButton JInsertEsp;
    private javax.swing.JButton JQueryButton;
    private javax.swing.JButton JQueryEsp;
    private javax.swing.JButton JUpdateButton;
    private javax.swing.JButton JUpdateEsp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
